services:
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}
        - REPO=trafex/nefiteasy-influxdb

script:
  - docker build -t $REPO:$COMMIT .

deploy:
    skip_cleanup: true
    branch: master
    commands:
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker push $REPO
